name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to release from
        required: true
        type: string
        default: main

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ inputs.branch }}

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24'

      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn format

  release:
    name: Release
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --frozen-lockfile

      - name: Build
        run: |
          git clone https://github.com/highlightjs/highlight.js.git
          cd highlight.js/extra
          git clone https://github.com/elastic/highlightjs-esql.git
          cd ..
          yarn install
          node ./tools/build.js -t node
          node ./tools/build.js -t cdn
          cd ..
          mkdir -p dist
          cp -r highlight.js/extra/highlightjs-esql/dist/* dist/

      - name: Release
        run: npx semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
